"""Add salary to users table

Revision ID: e446c11e6e32
Revises: f79d8b933277
Create Date: 2021-05-05 10:28:16.462463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e446c11e6e32'
down_revision = 'f79d8b933277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salary')
    # ### end Alembic commands ###
